# Generated by Django 3.2.6 on 2024-08-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
