# Generated by Django 3.2.6 on 2024-08-14 13:38

from django.db import migrations, models

def set_default_invoice(apps, schema_editor):
    InvoiceItem = apps.get_model('invoice', 'InvoiceItem')
    Invoice = apps.get_model('invoice', 'Invoice')
    default_invoice = Invoice.objects.first()  # Or select an appropriate invoice
    for item in InvoiceItem.objects.filter(invoice__isnull=True):
        item.invoice = default_invoice
        item.save()
class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20240814_1637'),
    ]

    operations = [
        migrations.RunPython(set_default_invoice),
    ]
