# Generated by Django 3.2.6 on 2024-08-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20240814_2052'),
    ]

    operations = [
    ]
